-- ### Trigger 3 : historiser_notes
-- **Action :** AFTER UPDATE sur INSCRIPTIONS (quand la note change)
-- **Fonction :** Enregistrer l'ancienne note dans une table d'historique

CREATE TABLE historique_notes (
    id_historique     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id       NUMBER NOT NULL,
    cours_id          NUMBER NOT NULL,
    ancienne_note     NUMBER,
    nouvelle_note     NUMBER,
    date_modification DATE DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER historiser_notes
AFTER UPDATE OF note on inscriptions
FOR EACH ROW
WHEN (OLD.note IS NOT NULL AND OLD.note <> NEW.note)
BEGIN
    INSERT INTO historique_notes(
        etudiant_id,
        cours_id,
        ancienne_note,
        nouvelle_note,
        date_modification
    ) VALUES(
        :OLD.etudiant_id,
        :OLD.cours_id,
        :OLD.note,
        :NEW.note,
        sysdate
    );
END;