CREATE SEQUENCE seq_departement START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_professeur START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_etudiant START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_cours START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_enseignement START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_inscription START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_salle START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;