DROP TABLE inscriptions CASCADE CONSTRAINTS;
DROP TABLE enseignements CASCADE CONSTRAINTS;
DROP TABLE cours CASCADE CONSTRAINTS;
DROP TABLE etudiants CASCADE CONSTRAINTS;
DROP TABLE professeurs CASCADE CONSTRAINTS;
DROP TABLE departements CASCADE CONSTRAINTS;
DROP TABLE salles CASCADE CONSTRAINTS;

DROP SEQUENCE seq_departement;
DROP SEQUENCE seq_professeur;
DROP SEQUENCE seq_etudiant;
DROP SEQUENCE seq_cours;
DROP SEQUENCE seq_enseignement;
DROP SEQUENCE seq_inscription;
DROP SEQUENCE seq_salle;

COMMIT;